; ========================================================
; This file was generated by NSISDialogDesigner 1.1.2.0
; http://coolsoft.altervista.org/nsisdialogdesigner
; ========================================================

Function fun_ApplicationConfig_RunRegister
  ExecWait '"$INSTDIR\ReportManagerRegister.exe" "AppConfig" "$INSTDIR" "$hCtl_ApplicationConfig_WSUrl_State" "$hCtl_ApplicationConfig_Domain_State" "$hCtl_ApplicationConfig_Account_State" "$hCtl_ApplicationConfig_Password_State" "$hCtl_ApplicationConfig_DataSource_State" "$hCtl_ApplicationConfig_Database_State" "$hCtl_ApplicationConfig_DBAccount_State" "$hCtl_ApplicationConfig_DBPassword_State"'
FunctionEnd

Function fun_WebServerConfig_RunRegister
  ExecWait '"$INSTDIR\ReportManagerRegister.exe" "WebServerConfig" "$INSTDIR" "$hCtl_WebServerConfig_TypeIIS_State" "$hCtl_WebServerConfig_TypeUWS_State" "$hCtl_WebServerConfig_SiteName_State" "$hCtl_WebServerConfig_Address_State" "$hCtl_WebServerConfig_Port_State"'
FunctionEnd

